class_name ParityChecks
extends RefCounted

## Loads the canonical golden vectors from parity/vectors/ (generated by the Expo
## side: `npm run vectors:export`) and asserts the GDScript rules core reproduces
## every one EXACTLY. This is the Godot half of the parity contract.
##
## run_all() returns an Array[String] of failure messages (empty == all green).
## Used by both the headless runner and the GUT suite.

# Resolve parity/vectors/ which lives one level above the Godot project root.
static func _vectors_dir() -> String:
	return ProjectSettings.globalize_path("res://").path_join("../parity/vectors")

static func _load(name: String) -> Variant:
	var path := _vectors_dir().path_join(name)
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("Cannot open vector file: " + path)
		return null
	var txt := f.get_as_text()
	f.close()
	return JSON.parse_string(txt)

# Numeric-tolerant deep equality (handles int/float mixing from JSON).
static func deep_equal(a: Variant, b: Variant) -> bool:
	var ta := typeof(a)
	var tb := typeof(b)
	var a_num := ta == TYPE_INT or ta == TYPE_FLOAT
	var b_num := tb == TYPE_INT or tb == TYPE_FLOAT
	if a_num and b_num:
		return absf(float(a) - float(b)) <= 1e-9 + 1e-9 * absf(float(b))
	if ta != tb:
		return false
	match ta:
		TYPE_DICTIONARY:
			if a.size() != b.size():
				return false
			for k in a:
				if not b.has(k):
					return false
				if not deep_equal(a[k], b[k]):
					return false
			return true
		TYPE_ARRAY:
			if a.size() != b.size():
				return false
			for i in a.size():
				if not deep_equal(a[i], b[i]):
					return false
			return true
		_:
			return a == b

static func _fail(out: Array, label: String, got: Variant, expect: Variant) -> void:
	out.append("%s\n    got:    %s\n    expect: %s" % [label, str(got), str(expect)])

# ── individual checks ───────────────────────────────────────────────────────────

static func check_rng(out: Array) -> void:
	var data: Dictionary = _load("rng.json")
	for seed in data["seeds"]:
		var rng := LobRNG.new(int(seed))
		var u32: Array = data["vectors"][str(int(seed))]["u32"]
		for i in u32.size():
			var got := rng.next_u32()
			if got != int(u32[i]):
				_fail(out, "rng seed=%d i=%d" % [int(seed), i], got, int(u32[i]))
				break

static func check_score_reels(out: Array) -> void:
	var data: Dictionary = _load("score_reels.json")
	for c in data["cases"]:
		var got := Evaluate.score_reels(c["reels"], float(c["lucidityMultiplier"]),
			bool(c["allowFreeSpinGrant"]), bool(c["pattern23Triple"]), bool(c["learningActive"]))
		if not deep_equal(got, c["expect"]):
			_fail(out, "score_reels " + str(c["reels"]), got, c["expect"])

static func check_rounding(out: Array) -> void:
	var data: Dictionary = _load("rounding.json")
	for c in data["cases"]:
		var got := floori(float(c["value"]) * float(c["multiplier"]) + 0.5)
		if got != int(c["expect"]):
			_fail(out, "rounding %s*%s" % [str(c["value"]), str(c["multiplier"])], got, int(c["expect"]))

static func check_evaluate(out: Array) -> void:
	var data: Dictionary = _load("evaluate.json")
	for c in data["cases"]:
		var input: Dictionary = (c["input"] as Dictionary).duplicate(true)
		input["rng"] = LobRNG.new(int(c["seed"]))
		var got := Evaluate.evaluate(input)
		if not deep_equal(got, c["expect"]):
			_fail(out, "evaluate seed=%d" % int(c["seed"]), got, c["expect"])

static func check_abilities(out: Array) -> void:
	var data: Dictionary = _load("abilities.json")
	for c in data["cases"]:
		var got: Dictionary
		match String(c["op"]):
			"reroll":
				got = Abilities.apply_reroll(c["reels"], int(c["reelIndex"]), LobRNG.new(int(c["seed"])),
					float(c["lucidityMultiplier"]), Symbols.symbol_weights(),
					bool(c["pattern23Triple"]), bool(c["learningActive"]), bool(c["allowFreeSpinGrant"]))
			"move":
				got = Abilities.apply_move_column(c["reels"], int(c["reelIndex"]), int(c["direction"]),
					float(c["lucidityMultiplier"]), bool(c["pattern23Triple"]), bool(c["learningActive"]),
					bool(c["allowFreeSpinGrant"]))
			"copy":
				got = Abilities.apply_copy_reel(c["reels"], int(c["sourceReel"]), int(c["targetReel"]),
					float(c["lucidityMultiplier"]), bool(c["pattern23Triple"]), bool(c["learningActive"]),
					bool(c["allowFreeSpinGrant"]))
		if not deep_equal(got, c["expect"]):
			_fail(out, "ability %s %s" % [String(c["op"]), str(c["reels"])], got, c["expect"])

static func check_dealer(out: Array) -> void:
	var data: Dictionary = _load("dealer_vectors.json")
	for c in data["pickDealerItems"]:
		var got: Variant = Dealer.pick_dealer_items(int(c["seed"]))
		if not deep_equal(got, c["expect"]):
			_fail(out, "pickDealerItems seed=%d" % int(c["seed"]), got, c["expect"])
	for c in data["evaluateDealerTrigger"]:
		var got := Dealer.evaluate_dealer_trigger(c["input"])
		if not deep_equal(got, c["expect"]):
			_fail(out, "evaluateDealerTrigger " + str(c["input"]), got, c["expect"])

static func check_bank(out: Array) -> void:
	var data: Dictionary = _load("bank.json")
	for c in data["cases"]:
		var run := {
			"neurons": 0,
			"lucidityCoins": int(c["run"]["lucidityCoins"]),
			"scoreEarned": int(c["run"]["scoreEarned"]),
		}
		var got := Endings.bank_run_to_meta(run, c["meta"], String(c["ending"]), int(c["now"]))
		if not deep_equal(got, c["expect"]):
			_fail(out, "bank " + String(c["label"]), got, c["expect"])

static func check_lucidity(out: Array) -> void:
	var data: Dictionary = _load("lucidity_restore.json")
	for c in data["cases"]:
		var inp: Dictionary = c["input"]
		var got := Lucidity.plan_gain(int(inp["prevCoins"]), int(inp["gain"]),
			inp["abilitiesUsed"], int(inp["seed"]))
		if not deep_equal(got, c["expect"]):
			_fail(out, "lucidity " + str(inp), got, c["expect"])

static func check_endings(out: Array) -> void:
	var data: Dictionary = _load("endings.json")
	for c in data["checkEnding"]:
		var run := { "neurons": int(c["input"]["neurons"]), "scoreEarned": int(c["input"]["scoreEarned"]), "lucidityCoins": 0 }
		var got: Variant = Endings.check_ending(run, {})
		if not deep_equal(got, c["expect"]):
			_fail(out, "checkEnding " + str(c["input"]), got, c["expect"])
	for c in data["checkExitEligibility"]:
		var run := { "lucidityCoins": int(c["input"]["lucidityCoins"]) }
		var meta := { "corruptionEverUsed": bool(c["input"]["corruptionEverUsed"]) }
		var got := Endings.check_exit_eligibility(run, meta)
		if got != bool(c["expect"]):
			_fail(out, "checkExitEligibility " + str(c["input"]), got, bool(c["expect"]))

static func run_all() -> Array:
	var out: Array = []
	check_rng(out)
	check_score_reels(out)
	check_rounding(out)
	check_evaluate(out)
	check_abilities(out)
	check_dealer(out)
	check_bank(out)
	check_lucidity(out)
	check_endings(out)
	return out
